* 4D input
* input = (batch_size, Channel_num, width, height)
* 각 샘플 및 채널에 대해 독립적으로 batch norm을 수행한다.
* https://pytorch.org/docs/stable/generated/torch.nn.BatchNorm2d.html

In [1]:
import torch

In [119]:
bn = torch.nn.BatchNorm2d(100)
# Without Learnable Parameters
x = torch.randn(1, 1, 2, 2)
x = torch.tensor([[[[1, 2], [3, 4]]]], dtype = torch.float32)
print(x)
bn = torch.nn.BatchNorm2d(1, affine=False)
y = bn(x)
print(y)

tensor([[[[1., 2.],
          [3., 4.]]]])
tensor([[[[-1.3416, -0.4472],
          [ 0.4472,  1.3416]]]])


In [38]:
(x - torch.mean(x))/(torch.std(x)+1e-05)

tensor([[[[-1.1619, -0.3873],
          [ 0.3873,  1.1619]]]])