In [22]:
import torch

In [23]:
flatten = torch.nn.Flatten()

In [24]:
x = torch.rand(2, 2, 2)
print(x.shape)
print(x)

torch.Size([2, 2, 2])
tensor([[[0.4563, 0.5697],
         [0.3550, 0.2251]],

        [[0.1369, 0.3181],
         [0.6756, 0.7958]]])


In [25]:
y = flatten(x)
print(y.shape)
print(y)

torch.Size([2, 4])
tensor([[0.4563, 0.5697, 0.3550, 0.2251],
        [0.1369, 0.3181, 0.6756, 0.7958]])


In [27]:
z = torch.flatten(x, start_dim=1)
z

tensor([[0.4563, 0.5697, 0.3550, 0.2251],
        [0.1369, 0.3181, 0.6756, 0.7958]])