* input size 유지
* 각 요소에 대해 양수로 변환

In [24]:
import torch

In [ ]:
relu = torch.nn.ReLU()

In [23]:
x = torch.tensor([-1, 0, 1])
print(x)

relu(x)

tensor([-1,  0,  1])


tensor([0, 0, 1])

In [20]:
y = torch.rand(3, 3)
print(y)

y -=torch.mean(y)
print(y)

relu(y)

tensor([[0.2576, 0.9119, 0.4379],
        [0.6923, 0.5695, 0.3422],
        [0.0588, 0.3765, 0.7416]])
tensor([[-0.2299,  0.4244, -0.0497],
        [ 0.2047,  0.0819, -0.1454],
        [-0.4288, -0.1111,  0.2540]])


tensor([[0.0000, 0.4244, 0.0000],
        [0.2047, 0.0819, 0.0000],
        [0.0000, 0.0000, 0.2540]])